SELECT 
    c.COLUMN_NAME, 
    tc.CONSTRAINT_TYPE, 
    tc.CONSTRAINT_NAME
FROM 
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS tc
JOIN 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS c
ON 
    tc.CONSTRAINT_NAME = c.CONSTRAINT_NAME
WHERE 
    tc.TABLE_NAME = 'Customer'
AND 
    tc.CONSTRAINT_TYPE = 'Foreign KEY';
