#!/usr/bin/env node
/**
 * Green Email Outreach — Campaign Report Generator
 * 
 * Usage:
 *   node report.js --log send-log.csv
 *   node report.js --log send-log.csv --output report.md
 */

const fs = require('fs');
const path = require('path');

function parseArgs() {
  const args = {};
  for (let i = 2; i < process.argv.length; i++) {
    if (process.argv[i] === '--log') args.log = process.argv[++i];
    if (process.argv[i] === '--output') args.output = process.argv[++i];
  }
  return args;
}

function parseCSV(filepath) {
  const content = fs.readFileSync(filepath, 'utf8');
  const lines = content.trim().split('\n');
  const headers = lines[0].split(',').map(h => h.trim().replace(/"/g, ''));
  return lines.slice(1).map(line => {
    const values = line.match(/(".*?"|[^,]+)/g) || [];
    const obj = {};
    headers.forEach((h, i) => { obj[h] = (values[i] || '').replace(/"/g, '').trim(); });
    return obj;
  });
}

function generateReport(logEntries) {
  const total = logEntries.length;
  const sent = logEntries.filter(e => e.status === 'sent').length;
  const failed = logEntries.filter(e => e.status === 'failed' || e.status === 'error').length;
  const skipped = logEntries.filter(e => e.status === 'skipped').length;
  
  // Group by template
  const byTemplate = {};
  logEntries.forEach(e => {
    const t = e.template || 'unknown';
    if (!byTemplate[t]) byTemplate[t] = { sent: 0, failed: 0 };
    byTemplate[t][e.status === 'sent' ? 'sent' : 'failed']++;
  });
  
  // Group by day
  const byDay = {};
  logEntries.forEach(e => {
    const day = e.timestamp ? e.timestamp.split('T')[0] : 'unknown';
    if (!byDay[day]) byDay[day] = { sent: 0, failed: 0 };
    byDay[day][e.status === 'sent' ? 'sent' : 'failed']++;
  });
  
  const successRate = total > 0 ? ((sent / total) * 100).toFixed(1) : '0.0';
  
  let report = `# Green Email Outreach — Campaign Report

**Generated:** ${new Date().toISOString()}

## Summary

| Metric | Count |
|--------|-------|
| Total Attempts | ${total} |
| Successfully Sent | ${sent} |
| Failed | ${failed} |
| Skipped | ${skipped} |
| Success Rate | ${successRate}% |

## By Template

| Template | Sent | Failed | Success Rate |
|----------|------|--------|-------------|
`;

  for (const [template, stats] of Object.entries(byTemplate)) {
    const tTotal = stats.sent + stats.failed;
    const tRate = tTotal > 0 ? ((stats.sent / tTotal) * 100).toFixed(1) : '0.0';
    report += `| ${template} | ${stats.sent} | ${stats.failed} | ${tRate}% |\n`;
  }
  
  report += `\n## By Day

| Date | Sent | Failed | Success Rate |
|------|------|--------|-------------|
`;

  for (const [day, stats] of Object.entries(byDay).sort()) {
    const dTotal = stats.sent + stats.failed;
    const dRate = dTotal > 0 ? ((stats.sent / dTotal) * 100).toFixed(1) : '0.0';
    report += `| ${day} | ${stats.sent} | ${stats.failed} | ${dRate}% |\n`;
  }
  
  report += `\n## Recent Activity (Last 10)

| Time | Email | Company | Status | Template |
|------|-------|---------|--------|----------|
`;

  logEntries.slice(-10).reverse().forEach(e => {
    const time = e.timestamp ? e.timestamp.replace('T', ' ').substring(0, 19) : 'N/A';
    report += `| ${time} | ${e.email || 'N/A'} | ${e.company || 'N/A'} | ${e.status} | ${e.template || 'N/A'} |\n`;
  });
  
  report += `\n---\n*Report generated by Green Email Outreach*
`;
  
  return report;
}

async function main() {
  const args = parseArgs();
  
  if (!args.log) {
    console.log('Usage: node report.js --log send-log.csv [--output report.md]');
    return;
  }
  
  if (!fs.existsSync(args.log)) {
    console.error(`Log file not found: ${args.log}`);
    return;
  }
  
  const logEntries = parseCSV(args.log);
  console.log(`📊 Analyzing ${logEntries.length} log entries...\n`);
  
  const report = generateReport(logEntries);
  
  if (args.output) {
    fs.writeFileSync(args.output, report);
    console.log(`📁 Report saved to ${args.output}`);
  } else {
    console.log(report);
  }
}

main().catch(e => { console.error('Error:', e.message); process.exit(1); });
